### ISSUE TITLE
Add monitoring for pilot IDRs and ancillary servers

### ISSUE THREAD

**Issue by manics** [IDR/deployment#264]
Add prometheus monitoring for pilot-proxy, all pilot IDRs (omeroreadwrite) and idrftp. This will require:
- [ ] Setup a management server that's connected to both the idrftp and pilot-idr networks. This will probably be part of the idr-proxy deployment since the proxy is already connected to all IDRs and is updated as part of the standard pilot deployment workflow. Therefore idr-ftp will require a change to it's networking and configuration to fit in but this shouldn't be too bad.
- [ ] Customising the current omeroreadwrite monitoring configuration to work with the pilot IDRs. This may not be too difficult if the management VM is on the pilot-idr network.
- [x] Short term fix: add disk space alerting to idrftp since this is the priority https://github.com/IDR/deployment/pull/265
- [ ] Add monitoring to idrftp
- [ ] Add alerting to the pilot management VM. Since this is a newish deployment we can use this as a way to experiment with the prometheus alerting rules.

Also
- [ ] Update main IDR deployments with new prometheus and prometheus-node roles. The latter may require Grafana dashboards to be updated since some metric names have changed. https://github.com/IDR/deployment/pull/281
- [x] Update postresql prometheus exporter (currently broken) https://github.com/IDR/deployment/issues/244

**Comment by joshmoore** [comment]
Along with #265, @manics, would it be possible to have a definitive list of monitoring ports and optimally URLs that one can use like http://localhost:9090/graph?g0.range_input=1h&g0.expr=(node_filesystem_avail_bytes%7Bmountpoint%3D%22%2Fdata%22%7D%20*%20100)%20%2F%20node_filesystem_size_bytes%7Bmountpoint%3D%22%2Fdata%22%7D&g0.tab=0 ?

**Comment by manics** [comment]
Other prometheus roles to be upgraded:
- https://github.com/ome/ansible-role-omero-web-django-prometheus/pull/4
- https://github.com/ome/ansible-role-prometheus-jmx/pull/4
