### ISSUE TITLE
New name `idr-ftp` for S3 access

### ISSUE THREAD

**Issue by joshmoore** [IDR/deployment#270]
Although we extensively discussed the `idr-s3` proxy server for the public Zarr data, I do not remember discussing the proxy server name for the `idr-upload` bucket. I had been probably wrongly `idr-s3` could be reused as well.

I also feel `idr-ftp.openmicroscopy.org/idr-upload` is confusing for submitters esp. if we keep maintaining a FTP service in parallel. As the scope of this PR is the public read-only `idr` bucket, I would not raise as a blocker but let's not sidestep this discussion before we start pointing submissions at the upload bucket.

_Originally posted by @sbesson in https://github.com/IDR/deployment/pull/269#discussion_r488186784_

**Comment by manics** [comment]
How about `idr-ftp.openmicroscopy.org/idr-upload` or `idr-submissions.openmicroscopy.org/idr-upload`?

**Comment by joshmoore** [comment]
I could see either of those, but the duplicate `idr-` really is jarring. Guess I should have spent more time on the original request for the `idr-upload` bucket naming.

**Comment by manics** [comment]
If there's no data in the `idr-upload` we can probably ask for it to be deleted and a new one created? Though the problem with just `upload` is it's a shared s3 server so it'll actually be `s3.embassy.ebi.ac.uk/upload`

**Comment by joshmoore** [comment]
> If there's no data in the `idr-upload` we can probably ask for it to be deleted and a new one created?

True, though I'd like to avoid churn if possible. Do we have a better name for that part?

**Comment by joshmoore** [comment]
Ok. Brainstorming a bit to get this moving again:

 * **idr-upload.o.org/idr-upload** (following the simple rule of `$bucket.o.org/$bucket`)
 * **idr-submissions.o.org/idr-upload** (because it's a submission...)
 * **ebi-proxy.o.org/idr-upload** (to make it clear where it's going)
 * **ebi-s3.o.org/idr-upload** (ditto)
 * **somerandomhostname.o.org/idr-upload** (whatever naming scheme like _fish_ in case we are going to need to do this for other buckets)
 * **private-s3.o.org/idr-upload** (something to make it clear that it won't be shared with anyone)
 * **secure.o.org/idr-upload** (ditto)
 * **s3.o.org/idr-upload** (to keep it as short as possible, accepting that we can do it better without our own buckets. This can only be used once, but perhaps this is the most important one)
 * **io.o.org** or **up.o.org** (equally short)

**Comment by manics** [comment]
My top 3 in alphabetical order:
- idr-submissions.o.org/idr-upload
- private-s3.o.org/idr-upload
- somerandomhostname.o.org/idr-upload

**Comment by sbesson** [comment]
Ideally, having been able to use `https://s3.embassy.ebi.ac.uk/idr-upload` directly would have been my preference.  Having the domain communicating the fact that it's an object store and some information about its location feels standard. In the list above, `ebi-s3.openmicroscopy.org/idr-upload` is probably the closest. An alternative would be `s3-embassy.openmicroscopy.org/idr-upload`.

**Comment by joshmoore** [comment]
One benefit of omitting "embassy" would be stability despite a possible move to FIRE.

**Comment by sbesson** [comment]
Closing for now as the  upload workflow has substantially changed and is using EMBL-EBI built-in transfer infrastructure.
