### ISSUE TITLE
'docker-python' package does not exist on Rocky9

### ISSUE THREAD

**Issue by dominikl** [IDR/deployment#416]
This causes an issue on Rocky9: https://github.com/IDR/deployment/blob/3876a0fc477c4021f6281bbf19967b886b6ee854/ansible/idr-docker.yml#L14 

```
TASK [install docker-python] *******************************************************************************************************************************************************
fatal: [2f5d1f82-2aad-433b-ab9f-98c5fe25ffa5]: FAILED! => {"changed": false, "failures": ["No package docker-python available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
```

The package on Rocky9 is called `python3-docker`. It'll need some OS check here. But I'm not familiar with ansible, don't know how to do that. I just manually changed it in order to spin up pilot-rocky9.

**Comment by sbesson** [comment]
Looking at c65824e38aef4a4683d7b60bd45294e374273113, this package might be have been a required of the former self-hosted analysis environment Should we try and drop it entirely?

**Comment by dominikl** [comment]
Initially I completely commented that out. But then a later step failed with an error that python docker was missing. Unfortunately I didn't keep track of it, but something else is relying on it (which might well be possible to be removed as well).

**Comment by sbesson** [comment]
See 19f3a0015d16f1223bc8547dbff55369a46007d3 added to #413

**Comment by dominikl** [comment]
👍 Thanks. Of course, I can just replaced, because IDR will be Rocky9 only.
