### ISSUE TITLE
Openstack may attempt to obtain a new floating IP instead of reusing it

### ISSUE THREAD

**Issue by manics** [IDR/deployment#54]
There are two stages to using a floating IP in Openstack:
1. Obtain an IP from a pool
2. Assign it to a server

If an IP is detached from a server it remains in the project and can be reused. This is important where the number of floating IPs is limited by quota.

The `os_server` module should automatically request or reuse IPs (`reuse_ips` defaults to `True`):
- http://docs.ansible.com/ansible/2.3/os_server_module.html
- used in https://github.com/IDR/ansible-role-openstack-idr-instance/blob/2.0.0/tasks/main.yml#L27

In practice it does on some clouds (UoD OME internal) but not others (EBI Embassy), which leads to misleading errors along the lines of "Floating IP quota exceeded" as it ignores an existing free IP. The current workaround is to manually assign the floating IP to the server, and re-run all playbooks.

**Comment by sbesson** [comment]
Have not seen many errors associated with floating IPs since the migration to Embassy Cloud v4. Closing
